services:
  nest-api-boilerplate:
    build:
      dockerfile: Dockerfile
    image: nest-api-boilerplate
    container_name: nest-api-boilerplate
    ports:
      - ${PORT}:${PORT}
    environment:
      - APP_ENV=${APP_ENV}
      - PORT=${PORT}
      - APP_SECRET=${APP_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      # Database
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      # Redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # LDAP
      - LDAP_URL=${LDAP_URL}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_CREDENTIALS=${LDAP_BIND_CREDENTIALS}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_SEARCH_FILTER=${LDAP_SEARCH_FILTER}
      # Caching
      - CACHE_TTL=${CACHE_TTL}
      # Log
      - LOG_FILE=${LOG_FILE}
      - ERR_LOG_FILE=${ERR_LOG_FILE}
      - ELASTICSEARCH=${ELASTICSEARCH}
      - ELASTICSEARCH_INDEX_PATTERN=${ELASTICSEARCH_INDEX_PATTERN}
    networks:
      - nest-api-boilerplate

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD:  ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    networks:
      - nest-api-boilerplate

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    restart: always
    privileged: true
    volumes:
      - /data/redis:/data
      - /usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /var/log/redis:/logs
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - nest-api-boilerplate

networks:
  nest-api-boilerplate:
    external: false